[package]
name = "git_status"
version = "0.1.0"
authors = ["Crandel <cradlemann@gmail.com>"]
edition = "2018"

license-file = "LICENSE"

[lib]
name = "git_status"
path = "src/lib.rs"

[dependencies]
regex = "1.3.1"